                            List of relations
 Schema |                    Name                    |   Type   | Owner  
--------+--------------------------------------------+----------+--------
 public | auth_group                                 | table    | axelor
 public | auth_group_meta_permissions                | table    | axelor
 public | auth_group_permissions                     | table    | axelor
 public | auth_group_roles                           | table    | axelor
 public | auth_group_seq                             | sequence | axelor
 public | auth_permission                            | table    | axelor
 public | auth_permission_seq                        | sequence | axelor
 public | auth_role                                  | table    | axelor
 public | auth_role_meta_permissions                 | table    | axelor
 public | auth_role_permissions                      | table    | axelor
 public | auth_role_seq                              | sequence | axelor
 public | auth_user                                  | table    | axelor
 public | auth_user_meta_permissions                 | table    | axelor
 public | auth_user_permissions                      | table    | axelor
 public | auth_user_roles                            | table    | axelor
 public | auth_user_seq                              | sequence | axelor
 public | base_wizard                                | table    | axelor
 public | base_wizard_seq                            | sequence | axelor
 public | dms_file                                   | table    | axelor
 public | dms_file_seq                               | sequence | axelor
 public | dms_file_tag                               | table    | axelor
 public | dms_file_tag_seq                           | sequence | axelor
 public | dms_file_tags                              | table    | axelor
 public | dms_permission                             | table    | axelor
 public | dms_permission_seq                         | sequence | axelor
 public | event_address                              | table    | axelor
 public | event_address_seq                          | sequence | axelor
 public | event_discount                             | table    | axelor
 public | event_discount_seq                         | sequence | axelor
 public | event_event                                | table    | axelor
 public | event_event_discount_list                  | table    | axelor
 public | event_event_event_registration_list        | table    | axelor
 public | event_event_registration                   | table    | axelor
 public | event_event_registration_seq               | sequence | axelor
 public | event_event_seq                            | sequence | axelor
 public | exception_trace_back                       | table    | axelor
 public | exception_trace_back_seq                   | sequence | axelor
 public | hibernate_sequence                         | sequence | axelor
 public | mail_address                               | table    | axelor
 public | mail_address_seq                           | sequence | axelor
 public | mail_flags                                 | table    | axelor
 public | mail_flags_seq                             | sequence | axelor
 public | mail_follower                              | table    | axelor
 public | mail_follower_seq                          | sequence | axelor
 public | mail_message                               | table    | axelor
 public | mail_message_recipients                    | table    | axelor
 public | mail_message_seq                           | sequence | axelor
 public | message_email_account                      | table    | axelor
 public | message_email_account_seq                  | sequence | axelor
 public | message_email_address                      | table    | axelor
 public | message_email_address_seq                  | sequence | axelor
 public | message_message                            | table    | axelor
 public | message_message_bcc_email_address_set      | table    | axelor
 public | message_message_cc_email_address_set       | table    | axelor
 public | message_message_reply_to_email_address_set | table    | axelor
 public | message_message_seq                        | sequence | axelor
 public | message_message_to_email_address_set       | table    | axelor
 public | message_template                           | table    | axelor
 public | message_template_seq                       | sequence | axelor
 public | meta_action                                | table    | axelor
 public | meta_action_menu                           | table    | axelor
 public | meta_action_menu_seq                       | sequence | axelor
 public | meta_action_seq                            | sequence | axelor
 public | meta_attachment                            | table    | axelor
 public | meta_attachment_seq                        | sequence | axelor
 public | meta_enum                                  | table    | axelor
 public | meta_enum_seq                              | sequence | axelor
 public | meta_field                                 | table    | axelor
 public | meta_field_seq                             | sequence | axelor
 public | meta_file                                  | table    | axelor
 public | meta_file_seq                              | sequence | axelor
 public | meta_filter                                | table    | axelor
 public | meta_filter_seq                            | sequence | axelor
 public | meta_help                                  | table    | axelor
 public | meta_help_seq                              | sequence | axelor
 public | meta_json_field                            | table    | axelor
 public | meta_json_field_roles                      | table    | axelor
 public | meta_json_field_seq                        | sequence | axelor
 public | meta_json_model                            | table    | axelor
 public | meta_json_model_roles                      | table    | axelor
 public | meta_json_model_seq                        | sequence | axelor
 public | meta_json_record                           | table    | axelor
 public | meta_json_record_seq                       | sequence | axelor
 public | meta_menu                                  | table    | axelor
 public | meta_menu_groups                           | table    | axelor
 public | meta_menu_roles                            | table    | axelor
 public | meta_menu_seq                              | sequence | axelor
 public | meta_model                                 | table    | axelor
 public | meta_model_seq                             | sequence | axelor
 public | meta_module                                | table    | axelor
 public | meta_module_depends                        | table    | axelor
 public | meta_module_seq                            | sequence | axelor
 public | meta_permission                            | table    | axelor
 public | meta_permission_rule                       | table    | axelor
 public | meta_permission_rule_seq                   | sequence | axelor
 public | meta_permission_seq                        | sequence | axelor
 public | meta_schedule                              | table    | axelor
 public | meta_schedule_param                        | table    | axelor
 public | meta_schedule_param_seq                    | sequence | axelor
 public | meta_schedule_seq                          | sequence | axelor
 public | meta_select                                | table    | axelor
 public | meta_select_item                           | table    | axelor
 public | meta_select_item_seq                       | sequence | axelor
 public | meta_select_seq                            | sequence | axelor
 public | meta_sequence                              | table    | axelor
 public | meta_translation                           | table    | axelor
 public | meta_translation_seq                       | sequence | axelor
 public | meta_view                                  | table    | axelor
 public | meta_view_custom                           | table    | axelor
 public | meta_view_custom_seq                       | sequence | axelor
 public | meta_view_groups                           | table    | axelor
 public | meta_view_seq                              | sequence | axelor
 public | team_task                                  | table    | axelor
 public | team_task_seq                              | sequence | axelor
 public | team_team                                  | table    | axelor
 public | team_team_members                          | table    | axelor
 public | team_team_roles                            | table    | axelor
 public | team_team_seq                              | sequence | axelor
 public | team_topic                                 | table    | axelor
 public | team_topic_seq                             | sequence | axelor
(120 rows)

